services:
  extractor:
    build: ./src/extractor
    environment:
      - PYTHONUNBUFFERED=1  # Print logs with buffering them
    volumes:
      - ./shared:/app
      - ./config.json:/app/config.json
    depends_on:
      - redis
    restart: on-failure
  detector:
    build: ./src/detector
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./shared:/app
      - ./src/models:/src/models:ro
      - ./config.json:/app/config.json
    depends_on:
      - redis
      - extractor
    ports:
      - 80:80 # webserver
      - 8080:8080 # trame/pyvista plotting
  # map:
  #   build: ./src/map
  redis:
    image: redis:alpine
volumes:
  shared: